get-android-apps: multi APK file interfaces: - listapk subcommand - singlwapk subcommand

diff --git a/get-android-apps b/get-android-apps
--- a/get-android-apps
+++ b/get-android-apps
@@ -3,10 +3,12 @@ pname=$(basename "$0")
 dname=$(dirname "$0")
 dotfile=$(ls ./dot-android-apps 2>/dev/null || echo ~/.android-apps)
 glitchlist=$(ls ./adb-backup-glitch.list 2>/dev/null || echo ~/etc/adb-backup-glitch.list)
-usage="$pname [OPTIONS] list [-{d|e|s|3}] [-u] [FILTER]
+usage="$pname [OPTIONS] list [-{d|e|s|3}] [-u] [PKG_FILTER]
 $pname [OPTIONS] apk PKGNAME [...]
 $pname [OPTIONS] ab PKGNAME [...]
 $pname [OPTIONS] data PKGNAME [...]
+$pname [OPTIONS] listapk [-{d|e|s|3}] [-u] [PKG_FILTER]
+$pname [OPTIONS] singleapk APKNAME [...]
 
 OPTIONS
   -s SERIAL
@@ -17,22 +19,27 @@ OPTIONS
     Only messages displayed, No SAADirectory is made.
 
 SUBCOMAMANDS
-  $pname list [-{d|e|s|3}] [-u] [FILTER]
-    List Android app's package names contains a string:FILTER to stdout.
+  $pname list [-{d|e|s|3}] [-u] [PKG_FILTER]
+  $pname listapk [-{d|e|s|3}] [-u] [PKG_FILTER]
+    List Android app's package names or APK file names for the packages which
+    name contains a string:PKG_FILTER to stdout.
     Suboptions:
       -d: filter to only show disabled packages
       -e: filter to only show enabled packages
       -s: filter to only show system packages
       -3: filter to only show third party packages
       -u: also include uninstalled packages
-      FILTER: package name template
+      PKG_FILTER: package name template
     Notes:
       default: show all packages
       -d -e: same as all packages
       -3 -s: same as all packages
   $pname apk PKGNAME [...]
     Copy Android app's APK files for PKGNAMEs to the current directory.
-    Each of APKs has the name as PKGNAME.apk, not the original.
+    Each of APKs has the name as PKGNAME-*.apk, not the original.
+  $pname apk APKNAME [...]
+    Copy Android app's APK files has designated APKNAME to the current
+    directory. The APKNAME must have the format as PKGNAME-*.apk.
   $pname ab PKGNAME [...]
     Get Android app's backup data images for PKGNAMEs to the current directory.
     Each of data files has the name as PKGNAME.ab, which is get by the
@@ -67,6 +74,38 @@ list_package_names() {
   adb_shell pm list packages$opts "$@" | sed 's/^package://' | sort
 }
 
+## list APK file names for desinated PKGNAMEs
+get_apk_names() {
+  test $# -eq 0 && { echo "$pname get_apk_names: Package name(s) required.">&2; return;}
+  
+  unset opts
+  while true; do
+    case "$1" in
+    -*) opts="$opts $1"; shift;;
+    *) break;;
+    esac
+  done
+  
+  for pkg; do
+    echo -n "$pkg: ">&2
+    local apkDir apkPath pkgName
+    local apkDirs=$(adb_shell pm path "$pkg" | sed 's/^package://;s/\r$//')
+    for apkDir in $apkDirs; do
+      for apkPath in $(run adb_shell ls "$apkDir"); do
+        pkgName=$(basename $(dirname "$apkPath") | sed 's/^\([^-]*\)-.*$/\1/')
+        echo "$pkgName-$(basename $apkPath)"
+      done
+    done
+    echo >&2
+  done
+}
+
+## list apps' APK files using pm or cmd package
+list_apk_names() {
+  IFS=$'\n' pkgnames=($(list_package_names "$@"))
+  get_apk_names "${pkgnames[@]}"
+}
+
 ## get each apps' apk using adb pull
 get_apks() {
   test $# -eq 0 && { echo "$pname apk: Package name(s) required.">&2; return;}
@@ -84,10 +123,35 @@ get_apks() {
     local apkPath apkPathes=$(adb_shell pm path "$pkg" | sed 's/^package://;s/\r$//')
     for apkPath in $apkPathes; do
       run_adb pull$opts "$apkPath" &&
-        mv $(basename "$apkPath") "$pkg-$(basename $apkPath .apk).apk"
+        mv $(basename "$apkPath") "$pkg-$(basename $apkPath)"
     done
     echo >&2
   done | grep '^[^[]'
+}
+
+## get each apps' apk using adb pull
+get_single_apk() {
+  test $# -eq 0 && { echo "$pname get_single_apk: APK name(s) required.">&2; return;}
+  
+  unset opts
+  while true; do
+    case "$1" in
+    -*) opts="$opts $1"; shift;;
+    *) break;;
+    esac
+  done
+  
+  for apk; do
+    local pkgName=$(echo $apk | sed 's/^\([^-]*\)-.*$/\1/')
+    local apkName=$(echo $apk | sed 's/^[^-]*-\(.*\)$/\1/')
+    echo "$pkgName: $apkName">&2
+    local apkPath apkPathes=$(adb_shell pm path "$pkgName" | sed 's/^package://;s/\r$//')
+    for apkPath in $apkPathes; do
+      test $(basename "$apkPath") = "$apkName" &&
+        run_adb pull$opts "$apkPath" &&
+         mv "$apkName" "$pkgName-$apkName"
+    done
+  done
 }
 
 ## get each apps' data using adb backup
@@ -246,7 +310,9 @@ devname=$(adb-parsedev model) || exit 20
 
 case "$cmd" in
 list) list_package_names "$@";;
+listapk) list_apk_names "$@";;
 apk) get_apks "$@";;
+singleapk) get_single_apk "$@";;
 ab) get_ab "$@";;
 data) get_data "$@";;
 *) echo "$pname: $cmd: unknown subcommand.">&2; exit 1;;
