indentation

diff --git a/get-android-apps b/get-android-apps
--- a/get-android-apps
+++ b/get-android-apps
@@ -2,7 +2,8 @@
 pname=$(basename "$0")
 dname=$(dirname "$0")
 dotfile=$(ls ./dot-android-apps 2>/dev/null || echo ~/.android-apps)
-glitchlist=$(ls ./adb-backup-glitch.list 2>/dev/null || echo ~/etc/adb-backup-glitch.list)
+glitchlist=$(ls ./adb-backup-glitch.list 2>/dev/null ||
+  echo ~/etc/adb-backup-glitch.list)
 usage="$pname [OPTIONS] list [-{d|e|s|3}] [-u] [PKG_FILTER [...]]
 $pname [OPTIONS] apk PKGNAME [...]
 $pname [OPTIONS] ab PKGNAME [...]
@@ -12,9 +13,11 @@ $pname [OPTIONS] singleapk APKNAME [...]
 
 OPTIONS
   -s SERIAL
-    use device with given serial number (overrides \$ANDROID_SERIAL), same as adb command
+    use device with given serial number (overrides \$ANDROID_SERIAL), same
+    as adb command.
   -v|--verbose
-    Additional messages are displayed. It has precedence over -q|--quiet|-s|--silent.
+    Additional messages are displayed. It has precedence over
+    -q|--quiet|-s|--silent.
   -n|--dryrun
     Only messages displayed, No SAADirectory is made.
 
@@ -41,9 +44,9 @@ SUBCOMAMANDS
     Copy Android app's APK files has designated APKNAME to the current
     directory. The APKNAME must have the format as PKGNAME-*.apk.
   $pname ab PKGNAME [...]
-    Get Android app's backup data images for PKGNAMEs to the current directory.
-    Each of data files has the name as PKGNAME.ab, which is get by the
-    'adb backup' command.
+    Get Android app's backup data images for PKGNAMEs to the current
+    directory. Each of data files has the name as PKGNAME.ab, which is get
+    by the 'adb backup' command.
   $pname data PKGNAME [...]
     (requires superuser permission)
     Get Android app's /data/data files' archives for PKGNAMEs to the current
@@ -79,7 +82,8 @@ list_package_names() {
 
 ## list APK file names for desinated PKGNAMEs
 get_apk_names() {
-  test $# -eq 0 && { echo "$pname get_apk_names: Package name(s) required.">&2; return;}
+  test $# -eq 0 &&
+    { echo "$pname get_apk_names: Package name(s) required.">&2; return;}
   
   unset opts
   while true; do
@@ -95,7 +99,8 @@ get_apk_names() {
     local apkDirs=$(adb_shell pm path "$pkg" | sed 's/^package://;s/\r$//')
     for apkDir in $apkDirs; do
       for apkPath in $(run adb_shell ls "$apkDir"); do
-        pkgName=$(basename $(dirname "$apkPath") | sed 's/^\([^-]*\)-.*$/\1/')
+        pkgName=$(basename $(dirname "$apkPath") |
+          sed 's/^\([^-]*\)-.*$/\1/')
         echo "$pkgName-$(basename $apkPath)"
       done
     done
@@ -111,7 +116,8 @@ list_apk_names() {
 
 ## get each apps' apk using adb pull
 get_apks() {
-  test $# -eq 0 && { echo "$pname apk: Package name(s) required.">&2; return;}
+  test $# -eq 0 &&
+    { echo "$pname apk: Package name(s) required.">&2; return;}
   
   unset opts
   while true; do
@@ -123,7 +129,8 @@ get_apks() {
   
   for pkg; do
     echo -n "$pkg: ">&2
-    local apkPath apkPathes=$(adb_shell pm path "$pkg" | sed 's/^package://;s/\r$//')
+    local apkPath
+    local apkPathes=$(adb_shell pm path "$pkg" | sed 's/^package://;s/\r$//')
     for apkPath in $apkPathes; do
       run_adb pull$opts "$apkPath" &&
         mv $(basename "$apkPath") "$pkg-$(basename $apkPath)"
@@ -134,7 +141,8 @@ get_apks() {
 
 ## get each apps' apk using adb pull
 get_single_apk() {
-  test $# -eq 0 && { echo "$pname get_single_apk: APK name(s) required.">&2; return;}
+  test $# -eq 0 &&
+    { echo "$pname get_single_apk: APK name(s) required.">&2; return;}
   
   unset opts
   while true; do
@@ -148,18 +156,21 @@ get_single_apk() {
     local pkgName=$(echo $apk | sed 's/^\([^-]*\)-.*$/\1/')
     local apkName=$(echo $apk | sed 's/^[^-]*-\(.*\)$/\1/')
     echo "$pkgName: $apkName">&2
-    local apkPath apkPathes=$(adb_shell pm path "$pkgName" | sed 's/^package://;s/\r$//')
+    local apkPath
+    local apkPathes=$(adb_shell pm path "$pkgName" |
+      sed 's/^package://;s/\r$//')
     for apkPath in $apkPathes; do
       test $(basename "$apkPath") = "$apkName" &&
         run_adb pull$opts "$apkPath" &&
-         mv "$apkName" "$pkgName-$apkName"
+          mv "$apkName" "$pkgName-$apkName"
     done
   done
 }
 
 ## get each apps' data using adb backup
 get_ab() {
-  test $# -eq 0 && { echo "$pname data: Package name(s) required.">&2;return;}
+  test $# -eq 0 &&
+    { echo "$pname data: Package name(s) required.">&2;return;}
   source "$dotfile"
   
   unset opts
@@ -182,10 +193,12 @@ get_ab() {
   for pkg; do
     while true; do
       echo -n "$pkg: ">&2
-      run_adb backup$opts -f "$pkg.ab" -noapk -noobb -noshared "$pkg" >/dev/null &
+      run_adb backup$opts -f "$pkg.ab" -noapk -noobb -noshared "$pkg" \
+        >/dev/null &
       sleep 1
       echo >&2
-      # workarounds for some glitch in between adb backup and sendkey on some devices
+      # workarounds for some glitch in between adb backup and sendkey on some
+      # devices
       if $retryp; then
         run adb-sendkey -v "$android_backup_password<tab><tab><enter>"
       else
@@ -232,7 +245,8 @@ get_datadir() {
 
 ## get each apps' /data/data directory snapshot using tar
 get_data() {
-  test $# -eq 0 && { echo "$pname data: Package name(s) required.">&2;return;}
+  test $# -eq 0 &&
+    { echo "$pname data: Package name(s) required.">&2;return;}
   source "$dotfile"
   
   unset opts
@@ -250,7 +264,6 @@ get_data() {
     echo -n "$pkg: ">&2
     dstfile=$pkg.tar.gz
     datadir=$(get_datadir "$pkg" "$pmdump") || continue
-    #echo -n "datadir=[$datadir]; ">&2
     test -n "$datadir" && adb_return_result $sucmd test -d "$datadir" || {
       echo "remote directory \"$datadir\" is not exist nor readbale.">&2
       continue
diff --git a/put-android-apps b/put-android-apps
--- a/put-android-apps
+++ b/put-android-apps
@@ -2,7 +2,8 @@
 pname=$(basename "$0")
 dname=$(dirname "$0")
 dotfile=$(ls ./dot-android-apps 2>/dev/null || echo ~/.android-apps)
-glitchlist=$(ls ./adb-backup-glitch.list 2>/dev/null || echo ~/etc/adb-backup-glitch.list)
+glitchlist=$(ls ./adb-backup-glitch.list 2>/dev/null ||
+  echo ~/etc/adb-backup-glitch.list)
 usage="$pname [OPTIONS] apk APKFILENAME [...]
 $pname [OPTIONS] ab ABFILENAME [...]
 $pname [OPTIONS] data ARCHIVEFILENAME [...]
@@ -23,26 +24,27 @@ SUBCOMAMANDS
     Multiple APK support: if one APK file of a multiple apk set appeared in
     commandline argument, the all correspondent APK are installed used with
     'adb install-multiple'.
-    Even if any two arguments point to same one APK set, then the installation
-    is done onetime per the APK set.
+    Even if any two arguments point to same one APK set, then the
+    installation is done onetime per the APK set.
   $pname ab ABFILENAME [...]
     Install Android app's backuped data image files (that is made with 'adb
     backup') to a remote Android device. There are some known glitches in
     execution of 'adb backup' or 'adb restore' on some Android device,
-    In one of such glitches (called 'Type 1 glitch'), the device ignores first
-    character of a backup/restore password send from the adb host computer by
-    'adb shell input' command except in case of first attempt of
+    In one of such glitches (called 'Type 1 glitch'), the device ignores
+    first character of a backup/restore password send from the adb host
+    computer by 'adb shell input' command except in case of first attempt of
     backup/restore.
     In another one of such glitches (called 'type 2 glitch'), the device
     requires inputting extra tab characters before the input of a
     backup/restore password.
-    When you want to apply this command on such devices, you have to write the
-    glitch-type-number and the device's name (you can obtain a device name from
-    an output of 'adb device -l' command as 'model:Pixel_4_XL') in the file:
-    $glitchdevs one at a line.
+    When you want to apply this command on such devices, you have to write
+    the glitch-type-number and the device's name (you can obtain a device
+    name from an output of 'adb device -l' command as 'model:Pixel_4_XL') in
+    the file: $glitchdevs one at a line.
   $pname data ARCHIVEFILENAME [...]
     Install Android app's data files (that is made with the 'get-android-apps
-    data' command) into the /data/data/*/ directory on a remote Android device.
+    data' command) into the /data/data/*/ directory on a remote Android
+    device.
     This subcommand is EXPERIMENTAL.
 "
 
@@ -72,13 +74,15 @@ put_apks() {
       echo -n "$apk: ">&2
       apkset_globs+=("$prefix")
       IFS=$'\n' apks=($(ls "$prefix"*))
-      test ${#apks[@]} = 0 && { echo "${prefix}*: file not exist.">&2; continue; }
+      test ${#apks[@]} = 0 &&
+        { echo "${prefix}*: file not exist.">&2; continue; }
       echo -n "--> "${apks[@]}": "
       IFS=$'\n' apks_w=($(cygpath -w "${apks[@]}"))
       run_adb install-multiple$opts "${apks_w[@]}"
     else
       echo -n "$apk: ">&2
-      test -s "$apk" || { echo "$apk: file not exist or size=0.">&2; continue; }
+      test -s "$apk" ||
+        { echo "$apk: file not exist or size=0.">&2; continue; }
       IFS=$'\n' apk_w=($(cygpath -w "$apk"))
       run_adb install$opts "${apk_w[@]}"
     fi
@@ -113,7 +117,8 @@ put_ab() {
     run_adb restore$opts "$(cygpath -w $ab)" >/dev/null &
     sleep 1
     echo >&2
-    # workaround for some glitch in between adb backup and sendkey on some devices
+    # workaround for some glitch in between adb backup and sendkey on some
+    # devices
     case "$glitchtype" in
     1) run adb-sendkey -v "0$android_backup_password<tab><tab><enter>";;
     2) run adb-sendkey -v "<tab><tab><tab><tab>$android_backup_password<tab><tab><enter>";;
@@ -126,7 +131,8 @@ put_ab() {
 
 ## put apps' data files into /data/data/PKGNAME/
 put_data() {
-  test $# -eq 0 && { echo "$pname data: archive file(s) required.">&2; return;}
+  test $# -eq 0 &&
+    { echo "$pname data: archive file(s) required.">&2; return;}
   source "$dotfile"
 
   unset opts
@@ -143,7 +149,8 @@ put_data() {
   for archive; do
     echo -n "$archive: ">&2
     pkg=$(basename ${archive%.tar.gz})
-    test -s "$archive" || { echo "$archive: file not exist or size=0.">&2; continue; }
+    test -s "$archive" ||
+      { echo "$archive: file not exist or size=0.">&2; continue; }
     datadir=$(adb_shell pm dump "$pkg"|sed -n '/^ *dataDir=/{s///;p;q;}')
     owner=$(adb_shell su -c ls -ld "$datadir" | awk '{print $2 ":" $3;}')
     
